// components/vue/App.vue
<template>
  <div class="fms-m-card-app" 
      :class="[this.mode === 'init' || this.mode === 'vue' ? '-mode-vue' : '-mode-default']">
      <h2 class="card-header">Vue.js</h2>
      <figure>
        <svg xmlns="http://www.w3.org/2000/svg" height="800" width="800" viewBox="-39.26295 -56.672 340.2789 340.032"><path fill="#41b883" d="M161.101 0l-30.224 52.35L100.652 0H0l130.877 226.688L261.753 0z"/><path fill="#34495e" d="M161.101 0l-30.224 52.35L100.652 0H52.351l78.526 136.01L209.403 0z"/></svg>
      </figure>
      <div class="fms-c-btn -small card-send" v-on:click="handleChangeMsg('Hej from Vue'),handleChangeMsgFrom('vue')">
        Send meassage
      </div>
      <div class="card-msg-mini">
        <span>MSG</span>{{msg}}
      </div>
      <div class="card-colors">
        <figure class="color-bg"></figure>
        <figure class="color-skin"></figure>
        <figure class="color-text"></figure>
      </div>
      <div class="fms-c-btn -xsmall -ghost card-theme" :class="[{'-disabled': this.isDisabled}]" v-on:click="handleChangeMode('vue')" >
        Apply theme
      </div>
  </div>
</template>

<script>
export default {
  name: 'app',
  data: () => ({
    msg: window.fms.msg,
    msgFrom: window.fms.msgFrom,
    mode: window.fms.mode,
    isDisabled: false
  }),
  mounted() {
    window.addEventListener('onChangeMsg', () => {
      this.msg = window.fms.msg;
    });
    window.addEventListener('onChangeMode', () => {
      if(window.fms.mode !== 'vue'){
        this.isDisabled = false
      } else {
        this.isDisabled = true
      }
      this.mode = window.fms.mode;
    });
    window.addEventListener('onChangeMsgFrom', () => {
      this.msgFrom = window.fms.msgFrom;
    });
  },
  methods: {
    handleChangeMsg : (newMsg) => {
      window.fms.changeMsg(newMsg);
    },
    handleChangeMsgFrom : (newFrom) => {
      window.fms.changeMsgFrom(newFrom);
    },
    handleChangeMode : (newMode) => {
      window.fms.changeMode(newMode);
    }
  }
}
</script>

// components/svelte/App.svelte
<script>
  import { onMount } from 'svelte';

  let msg = window.fms.msg;
  let msgFrom = window.fms.msgFrom;
  let mode = window.fms.mode;
  let isDisabled = false;

  function handleChangeMsg(){
    window.fms.changeMsg('Hello from Svelte');
  };
  function handleChangeMsgFrom(){
    window.fms.changeMsgFrom('svelte');
  };
  function handleChangeMode(e){
      window.fms.changeMode('svelte');
  };

  onMount(() => {
    window.addEventListener('onChangeMsg', () => {
      msg = window.fms.msg;
    });
    window.addEventListener('onChangeMode', () => {
      if(window.fms.mode !== 'svelte'){
        isDisabled = false
      } else {
        isDisabled = true
      }
      mode = window.fms.mode;
    });
    window.addEventListener('onChangeMsgFrom', () => {
      msgFrom = window.fms.msgFrom;
    });
  });

</script>

<div class="fms-m-card-app {mode === 'init' || mode === 'svelte' ? '-mode-svelte' : '-mode-default'}"
>
    <h2 class="card-header">Svelte.js</h2>
    <figure class="svelte-logo">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 98.1 118" style="enable-background:new 0 0 98.1 118;" xml:space="preserve">
        <style type="text/css">
          .st0{fill:#FF3E00;}
          .st1{fill:#FFFFFF;}
        </style>
        <path class="st0" d="M91.8,15.6C80.9-0.1,59.2-4.7,43.6,5.2L16.1,22.8C8.6,27.5,3.4,35.2,1.9,43.9c-1.3,7.3-0.2,14.8,3.3,21.3  c-2.4,3.6-4,7.6-4.7,11.8c-1.6,8.9,0.5,18.1,5.7,25.4c11,15.7,32.6,20.3,48.2,10.4l27.5-17.5c7.5-4.7,12.7-12.4,14.2-21.1  c1.3-7.3,0.2-14.8-3.3-21.3c2.4-3.6,4-7.6,4.7-11.8C99.2,32.1,97.1,22.9,91.8,15.6"/>
        <path class="st1" d="M40.9,103.9c-8.9,2.3-18.2-1.2-23.4-8.7c-3.2-4.4-4.4-9.9-3.5-15.3c0.2-0.9,0.4-1.7,0.6-2.6l0.5-1.6l1.4,1  c3.3,2.4,6.9,4.2,10.8,5.4l1,0.3l-0.1,1c-0.1,1.4,0.3,2.9,1.1,4.1c1.6,2.3,4.4,3.4,7.1,2.7c0.6-0.2,1.2-0.4,1.7-0.7L65.5,72  c1.4-0.9,2.3-2.2,2.6-3.8c0.3-1.6-0.1-3.3-1-4.6c-1.6-2.3-4.4-3.3-7.1-2.6c-0.6,0.2-1.2,0.4-1.7,0.7l-10.5,6.7  c-1.7,1.1-3.6,1.9-5.6,2.4c-8.9,2.3-18.2-1.2-23.4-8.7c-3.1-4.4-4.4-9.9-3.4-15.3c0.9-5.2,4.1-9.9,8.6-12.7l27.5-17.5  c1.7-1.1,3.6-1.9,5.6-2.5c8.9-2.3,18.2,1.2,23.4,8.7c3.2,4.4,4.4,9.9,3.5,15.3c-0.2,0.9-0.4,1.7-0.7,2.6l-0.5,1.6l-1.4-1  c-3.3-2.4-6.9-4.2-10.8-5.4l-1-0.3l0.1-1c0.1-1.4-0.3-2.9-1.1-4.1c-1.6-2.3-4.4-3.3-7.1-2.6c-0.6,0.2-1.2,0.4-1.7,0.7L32.4,46.1  c-1.4,0.9-2.3,2.2-2.6,3.8s0.1,3.3,1,4.6c1.6,2.3,4.4,3.3,7.1,2.6c0.6-0.2,1.2-0.4,1.7-0.7l10.5-6.7c1.7-1.1,3.6-1.9,5.6-2.5  c8.9-2.3,18.2,1.2,23.4,8.7c3.2,4.4,4.4,9.9,3.5,15.3c-0.9,5.2-4.1,9.9-8.6,12.7l-27.5,17.5C44.8,102.5,42.9,103.3,40.9,103.9"/>
        </svg>
    </figure>
    <div class="fms-c-btn -small card-send" on:click={handleChangeMsg} on:click={handleChangeMsgFrom} >
      Send meassage
    </div>
    <div class="card-msg-mini">
      <span>MSG</span>{msg}
    </div>
    <div class="card-colors">
      <figure class="color-bg"></figure>
      <figure class="color-skin"></figure>
      <figure class="color-text"></figure>
    </div>
    <div class="fms-c-btn -xsmall -ghost card-theme" class:-disabled={isDisabled} on:click={handleChangeMode} >
      Apply theme
    </div>
</div>
